version: '3'
services:
  backend:
    image: backend-smart-eats
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    volumes:
      - .env:/app/.env
