name: BACKEND - Build and test

on:
  push:
    working-directory: ./

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"
      - name: Install Dependencies
        run: yarn install

      - name: install typescript
        run: yarn add typescript

      - name: Build Application
        run: yarn build
        env:
          EDAMAM_API_KEY: ${{ secrets.EDAMAM_API_KEY }}
          EDAMAM_API_ID: ${{ secrets.EDAMAM_API_ID }}
          EDAMAM_URL: ${{ secrets.EDAMAM_URL }}
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
          PORT: ${{ secrets.PORT }}
  test:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"
      - name: Install Dependencies
        run: yarn install
      - name: Run tests
        run: yarn test
        env:
          EDAMAM_API_KEY: ${{ secrets.EDAMAM_API_KEY }}
          EDAMAM_API_ID: ${{ secrets.EDAMAM_API_ID }}
          EDAMAM_URL: ${{ secrets.EDAMAM_URL }}
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
          PORT: ${{ secrets.PORT }}